/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.prd.toml --include-runtime=false` (hash: 5d0cfa848e5552b200f90257c103c7cc)
interface __BaseEnv_Env {
	MCP_ALLOWED_HOSTNAMES: "mcp.8gnc.io";
	MCP_ALLOWED_ORIGIN_HOSTNAMES: "chatgpt.com,chat.openai.com,platform.openai.com";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MCP_ALLOWED_HOSTNAMES" | "MCP_ALLOWED_ORIGIN_HOSTNAMES">> {}
}
